### ISSUE TITLE
[WPKG-GP] Problem with windows 10

### ISSUE THREAD

**Issue by theLOICofFRANCE** [sonicnkt/wpkg-gp#2]
Hello,

First thank you for your work.

The client does not work at startup:
```
2018-11-27 11:50:38,848 - WpkgService - DEBUG - Testing connection: successful
2018-11-27 11:50:38,848 - WpkgService - DEBUG - Config: Reading ConnectionSleepBeforeRetry: '5' from ini file
2018-11-27 11:50:38,848 - WpkgService - DEBUG - Config: Reading ConnectionTries: '7' from ini file
2018-11-27 11:50:38,848 - WpkgService - DEBUG - Trying to connect to share. 1 of 7
2018-11-27 11:50:39,190 - WpkgService - ERROR - Error when processing Named Pipe Client:
Traceback (most recent call last):
  File "WpkgServer.pyc", line 195, in DoProcessClient
  File "WpkgExecuter.pyc", line 96, in Execute
  File "WpkgNetworkHandler.pyc", line 85, in connect_to_network_share
error: (58, 'WNetAddConnection2', 'Le serveur sp\xe9cifi\xe9 ne peut pas ex\xe9cuter l\x92op\xe9ration demand\xe9e.')
```

Manual launch does not work: 
```
C:\Program Files\Wpkg-GP>wpkgpipeclient.exe -d ExecuteNoReboot
Initializing Wpkg-GP software installation

C:\Program Files\Wpkg-GP>Wpkg-GP-Test.exe
2018-11-27 12:05:29 Starting OpenSCManager
2018-11-27 12:05:29 Started OpenSCManager
2018-11-27 12:05:29 Starting OpenService
2018-11-27 12:05:29 Started OpenService
2018-11-27 12:05:29 Starting QueryServiceStatusEx
2018-11-27 12:05:29 Finished QueryServiceStatusEx
2018-11-27 12:05:29 Checking the status of the service
2018-11-27 12:05:29 Trying to run CreateFile on named pipe
2018-11-27 12:05:29 The pipe handle was valid, continuing
2018-11-27 12:05:29 Executing SetNamedPipeHandleState
2018-11-27 12:05:29 Sending message to pipe server
2018-11-27 12:05:29 Waiting for reply from pipe server
2018-11-27 12:05:29 Executing ReadFile on pipe
2018-11-27 12:05:29 Successfully read from pipe, retrieved Status Code 100
2018-11-27 12:05:29 Converting string to wchar_t
2018-11-27 12:05:29 Calling UpdateStatus
2018-11-27 12:05:29 Running UpdateStatus with no error code
2018-11-27 12:05:29 Info (no event log): Initializing Wpkg-GP software installation
2018-11-27 12:05:29 Executing ReadFile on pipe
2018-11-27 12:05:29 Other end closed the pipe, continuing
```

The following change in the register did not work:
`REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power" /V HiberbootEnabled /T REG_dWORD /D 0 /F`

The same thing:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon]
"GpNetworkStartTimeoutPolicyValue"=dword:00000060
[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManWorkstation\Parameters]
"DNSNameResolutionRequired"=dword:00000000
"DomainCompatibilityMode"=dword:00000001
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths]
"\\\\*\\netlogon"="RequireMutualAuthentication=0,RequireIntegrity=0,RequirePrivacy=0"
```

On the other hand, this works well:
```
set SOFTWARE=\\192.168.182.1\wpkg\softwares
set WPKGROOT=\\192.168.182.1\wpkg\
cscript \\192.168.182.1\wpkg\wpkg.js /synchronize /nonotify /quiet
```

Do you have any idea how to fix this? In the worst case, I'll use the task scheduler...

**Comment by sonicnkt** [comment]
Hi, does this happenwith the latest Windows 10 Updates installed?

I heard in a few places that with the latest releases wpkg-gp isnt working on bootup anymore correctly.
From the error message it seems that network is available but for some reason its not possible to connect to the share. 

We are using Windows 10 LTSB and i WPKG-GP is still working fine here but i know ltsb is definatly not a option for everybody.

Another solution would be to trigger WPKG-GP as logon script.  I could add an option to wpkg-gp client that would also give visuals of the programm. i will put it on my todo list but i cant promise anything.

**Comment by theLOICofFRANCE** [comment]
@sonicnkt 
> does this happenwith the latest Windows 10 Updates installed?

I use the latest version (version 1809 pro x64).
Let's just say you saved a little time ^^ 

> Another solution would be to trigger WPKG-GP as logon script. I could add an option to wpkg-gp client that would also give visuals of the programm. i will put it on my todo list but i cant promise anything.

That would be great. On my side I will try to find the source of the problem.

Thank you for your answer.

**Comment by fuse59** [comment]
Hello,
We use also the latest Windows 10 (1809 pro x64 french) and no problems. The only problem was with the share configuration on a samba 3 server because the protocol smb 1 is deprecated and by defaut on 1809 is disabled (since 1803). We have migrated the samba server to samba 4 with protocol smb 3 and problem solved. You can also reactived the smb 1 on the client but not a good idea.

**Comment by theLOICofFRANCE** [comment]
Hello @fuse59 

Okay, I'll run a test for add in the [global] section of smb.conf the following line:
`min protocol = SMB2`

I'll monitor from the server with LSOF to see what's going on.

What surprises me most is that the following command works without modifing the server (Ubuntu Server 16.04 with samba 4.3.11):
`cscript \\192.168.182.1\wpkg\wpkg.js /synchronize /nonotify /quiet`

I'll try it soon, thanks for the feedback :)

**Comment by theLOICofFRANCE** [comment]
It still doesn't work for me and on 2 PCs with Windows 10 18.09.

Also tested without success:
`client min protocol = SMB3`

And with WPKG Client, settings report.txt:
```
Testing complete

1 - OK
1 - failed
6 - not tested

Details:

Action: Connecting to \\192.168.182.1\wpkg\wpkg.js as 
Result: [FAILED]
Message: WNetAddConnection2-> The specified server cannot perform the requested operation.

Action: Trying to read \\192.168.182.1\wpkg\wpkg.js
Result: [OK]
Message: 
```

My last tests with Wpkg-GP-Test.exe gave the same error:
```
2018-12-20 11:31:09 Running UpdateStatus with no error code
2018-12-20 11:31:09 Info (no event log): Initializing Wpkg-GP software installation
2018-12-20 11:31:09 Executing ReadFile on pipe
2018-12-20 11:31:09 Successfully read from pipe, retrieved Status Code 200
2018-12-20 11:31:09 Converting string to wchar_t
2018-12-20 11:31:09 Calling UpdateStatus
2018-12-20 11:31:09 Running UpdateStatus with no error code
2018-12-20 11:31:09 Info (no event log): Wpkg returned an error: Erreur CScript: ?chec du chargement du script "\\192.168.182.1\wpkg\wpkg.js" (Le serveur sp?cifi? ne peut pas ex?cuter l'op?ration demand?e. ).
2018-12-20 11:31:09 Executing ReadFile on pipe
2018-12-20 11:31:09 Other end closed the pipe, continuing
```

**Comment by theLOICofFRANCE** [comment]
@fuse59 Can you please share your smb.conf and Wpkg-gp.ini files so I can compare?

Have you installed Windows 10 1809 from an installation media?

Thanks.

**Comment by Link2Twenty** [comment]
Maybe a silly question but, if you try to file browse to `\\192.168.182.1\wpkg` does it work, from a problematic PC?

**Comment by theLOICofFRANCE** [comment]
@Link2Twenty  yes, browsing the network share works.
This is a specific problem with Windows 10 and wpkg because I can browse the sharing and use CScript from a command prompt.

**Comment by Link2Twenty** [comment]
OK, I thought maybe SMBv1 might have been disabled

You could check with this just to make sure, but it does sound like that's not the issue.

Administrative powershell
```powershell
(Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol).state
```

**Comment by theLOICofFRANCE** [comment]
SMBv1 is not installed by default from Windows 10 version 1709.
On my Windows 7 PCs, I disabled SMB v1 via the registry and they still work.

**Comment by theLOICofFRANCE** [comment]
Good morning,

I'm moving forward. First, Samba 4.3.11 delivered in Ubuntu 16.04.5 LTS does not know SMB3_11 which is now used by Windows 10 !
```
smbstatus -b

PID     Username      Group         Machine            Protocol Version       
------------------------------------------------------------------------------
9483      nobody        nogroup       192.168.182.228 (ipv4:192.168.182.228:49712) Unknown (0x0311)
```

Bug report opened in Ubuntu:
https://bugs.launchpad.net/ubuntu/+source/samba4/+bug/1736940/comments/14
https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1697817/comments/11

Concerning WPKG-GP, I have seen several times that people re-enabled SMB v1 to make it work with recent Windows 10 versions (From line 33 to 40):
https://github.com/SambaEdu/sambaedu-client-windows/blob/master/sources/var/se3/unattended/install/os/netinst/se3w10s-1.cmd
https://dev-eole.ac-dijon.fr/projects/eole-fichier/repository/revisions/359591ae55e30955d4778e56bfe7d2b675d7d97e

Indeed, by forcing version SMB v1 it works:
`9053      nobody        nogroup       192.168.182.228 (ipv4:192.168.182.228:49675) NT1   `

No parameters changes in the registry or in powershell (Set-smbserverconfiguration,Set-smbclientconfiguration) has been successful in running WPKG-GP with SMB2 and SMB3 and Windows 10 1809....

Enabling SMB v1 in windows 10 allows WPKG-GP to work but it is at the expense of windows security....

I don't know if the problem exists with Windows 1809 and the Samba version of Ubuntu 18.04.1 LTS.

**Comment by fuse59** [comment]
Hello,
for me no problems with Debian Stretch and Samba 4.5.12, it works fine. 

My configuration :

[global]
                netbios name = wpkg1
                workgroup = MAINTENANCE
                server string = %h server
                interfaces = ens192
                bind interfaces only = Yes
                map to guest = Bad User
                obey pam restrictions = Yes
                passwd program = /usr/bin/passwd %u
                passwd chat = *Enter\snew\sUNIX\spassword:* %n\n *Retype\snew\sUNIX\spassword:* %n\n *password\supdated\ssuccessfully* .
                syslog = 0
                log file = /var/log/samba/log.%m
                log level = 0
                max log size = 1000
                deadtime = 5
                os level = 255
                preferred master = Yes
                dns proxy = No
                wins support = Yes
                panic action = /usr/share/samba/panic-action %d
                idmap config * : backend = tdb
                load printers = No
                invalid users = root
                acl allow execute always = True
                client min protocol = SMB2_10

[wpkg]
        path = /data/wpkg-motor
        valid users = @group, wpkg-agent
        write list = @group
        read only = Yes
        max connections = 1000
        browseable = No
        create mask = 0664
        directory mask = 0775

[wpkg-log]
        path = /data/wpkg-log
        valid users = @group, wpkg-agent
        write list = @group, wpkg-agent
        read only = Yes
        max connections = 1000
        browseable = No
        create mask = 0664
        directory mask = 0775

[wpkgrepo]
        path = /data/wpkg-repository
        write list = user
        guest ok = Yes
        read only = Yes
        max connections = 1000
        browseable = No
        create mask = 0664
        directory mask = 0775

**Comment by theLOICofFRANCE** [comment]
If I understand correctly, in order not to be disturbed with the latest Windows 10, we must use a version of Samba > 4.7.0
https://www.samba.org/samba/history/samba-4.7.0.html

@fuse59 Hello :)

Thank you for the feedback! I'll see if Debian has backported some corrections.

Otherwise I might try to see a 'do-release-upgrade' in ubuntu to see if WPKG-GP works without SMB v1.

Thanks !

**Comment by theLOICofFRANCE** [comment]
@fuse59 

Indeed, unlike Ubuntu, Debian recognizes SMB3_11 ;)

[Samba_Ubuntu_vs_Debian.diff.txt](https://github.com/sonicnkt/wpkg-gp/files/2726638/Samba_Ubuntu_vs_Debian.diff.txt)
