### ISSUE TITLE
RFE: Execute Additional Commands

### ISSUE THREAD

**Issue by klou** [sonicnkt/wpkg-gp#3]
My usage case is to copy the client's ```wpkg.xml``` to a network share (to be parsed for WpkgReports).  
I currently use a separate BAT file.

Instead of passing a *.bat file to ```WpkgCommand``` in ```WPKG-GP.ini```, it would be nice to specify additional commands separately from the call to ```wpkg.js```.  This would allow me to keep everything in one place ...

I've tried concatenating the ```cscript.exe wpkg.js & xcopy.exe wpkg.xml``` commands as ```WpkgCommand```, but ```subprocess.pyc``` throws an error.  I think that it is unable to process shell commands (```shell=True```)

https://stackoverflow.com/questions/3022013/windows-cant-find-the-file-on-subprocess-call

```
2019-12-02 17:06:04,267 - WpkgService - ERROR - Error when processing Named Pipe Client:
Traceback (most recent call last):
  File "WpkgServer.pyc", line 207, in DoProcessClient
  File "WpkgExecuter.pyc", line 233, in Execute
  File "subprocess.pyc", line 711, in __init__
  File "subprocess.pyc", line 959, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
```

Minor request ...

**Comment by sonicnkt** [comment]
Should be to hard to implement additional commands before the network share is unmounted again. 
I also thought a but adding the option to add a command before the execution of wpkg (for some special network mounts). 
Sadly i dont have a lot of time in the moment to work on this. We are renovating right now and lots of work i had put into this was on my free time. But im planning to work on this (and the client) again next year and will add this to my list.
